"""add thumbnail field to posts

Revision ID: de96aa327772
Revises: 2ecb2ee290d4
Create Date: 2026-02-22 10:59:29.855686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de96aa327772'
down_revision: Union[str, None] = '2ecb2ee290d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('featured_posts', 'post_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('uq_week_post', 'featured_posts', type_='unique')
    op.add_column('posts', sa.Column('thumbnail', sa.String(), nullable=True))
    op.alter_column('posts', 'blog_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_posts_blog', table_name='posts')
    op.drop_index('idx_posts_published', table_name='posts')
    op.drop_constraint('uq_blog_link', 'posts', type_='unique')
    op.create_index('idx_blog_id', 'posts', ['blog_id'], unique=False)
    op.create_index('idx_published_at', 'posts', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_published_at', table_name='posts')
    op.drop_index('idx_blog_id', table_name='posts')
    op.create_unique_constraint('uq_blog_link', 'posts', ['blog_id', 'link'])
    op.create_index('idx_posts_published', 'posts', ['published_at'], unique=False)
    op.create_index('idx_posts_blog', 'posts', ['blog_id'], unique=False)
    op.alter_column('posts', 'blog_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('posts', 'thumbnail')
    op.create_unique_constraint('uq_week_post', 'featured_posts', ['week_start', 'post_id'])
    op.alter_column('featured_posts', 'post_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
